### ISSUE TITLE
Invalid publication date

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-misc#4]
https://github.com/ietf-ribose/relaton-data-misc/blob/1f9465d443de097c8be6dac02f1db2b74eddace0/data/reference.IEEE.802-11A.1999.yaml#L27

**Comment by ronaldtse** [comment]
@strogonoff this is from the original data. However, I just noticed that this document is actually available in the new IEEE data set:
https://github.com/ietf-ribose/relaton-data-ieee/blob/main/data/IEEE_802-11A.1999.yaml

Can we map the ones from the `misc` dataset to their new counterparts and remove this old file from `misc`?

**Comment by strogonoff** [comment]
I can say that the service supports manual mapping of xml2rfc to document ID via management GUI…

**Comment by strogonoff** [comment]
If we want to keep some of these documents, we must adjust Relaton YAML output so that it does not output `-00` prefix. This is not supported by the spec. They can output just the year, but if they output a month it must be a valid month.

**Comment by strogonoff** [comment]
@ronaldtse

1. The issue is that the code that generates YAML apparently does not validate the dates it writes.

2. It’s not just IEEE:

    ```
    ./data/reference.ITU.I361.1993.yaml:  value: 1993-00
    ./data/reference.ITU.I361.1993.yaml:revdate: 1993-00
    ./data/reference.IEEE.802-11H.2003.yaml:  value: 2003-00
    ./data/reference.IEEE.802-11H.2003.yaml:revdate: 2003-00
    ./data/reference.IEEE.802-11B.1999.yaml:  value: 1999-00
    ./data/reference.IEEE.802-11B.1999.yaml:revdate: 1999-00
    ./data/reference.ITU.I363.1993.yaml:  value: 1993-00
    ./data/reference.ITU.I363.1993.yaml:revdate: 1993-00
    ./data/reference.IEEE.802-11F.2003.yaml:  value: 2003-00
    ./data/reference.IEEE.802-11F.2003.yaml:revdate: 2003-00
    ./data/reference.IEEE.802-11A.1999.yaml:  value: 1999-00
    ./data/reference.IEEE.802-11A.1999.yaml:revdate: 1999-00
    ./data/reference.IEEE.802-11G.2003.yaml:  value: 2003-00
    ./data/reference.IEEE.802-11G.2003.yaml:revdate: 2003-00
    ./data/reference.IEEE.802-11D.2001.yaml:  value: 2001-00
    ./data/reference.IEEE.802-11D.2001.yaml:revdate: 2001-00
    ```

**Comment by ronaldtse** [comment]
This is clearly a bug with Relaton. @andrew2net can you check this?

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
